language: python
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
install:
  - python3 -m pip install tox
script:
  - tox
